python3: can't open file 'teste.py': [Errno 2] No such file or directory
Unable to init server: Could not connect: Connection refused
Unable to init server: Não foi possível conectar: Connection refused

(makeGraphs.py:199771): Gdk-CRITICAL **: 13:27:33.243: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
